### ISSUE TITLE
Permission to evaluation results on academic repository

### ISSUE THREAD

**Issue by abdkhanstd** [jiajingchen113322/ViewNet#3]
Thank you for your outstanding contributions, and we sincerely value the effort you've invested. We have evaluated various datasets and configurations. I kindly request your permission to share these results on a repository I intend to create for academic purposes, including other implementations on other repositories. Your consideration is greatly appreciated.

**Comment by jiajingchen113322** [comment]
Sorry for the late response, please feel free to use it as you want, thanks!
